version: '3.7'
services:

  html2image:
    container_name: html2image
    build: ../
    image: html2image
    restart: always
    ports:
      - "22233:22233"
    networks:
      backend: {}

networks:
  backend:
    external: true
