version: '3.7'
services:

  html2image:
    container_name: html2image
    build: .
    image: adele.html2image
    restart: always
    networks:
      backend: {}

networks:
  backend:
    external: true
